mode: train
device: cpu
batch_size: 128
learning_rate: 0.001
learning_rate_halving: true
learning_rate_patience: 3
learning_rate_performance_epsilon: 0.01
embedding_dim: 50
linSource_dim: 128
linTarget_dim: 64
lin1_dim: 200
activation: gelu
optimizer: adam
momentum: 0.9
weight_decay: 0.0
adam_beta1: 0.9
adam_beta2: 0.999
epochs: 10
log_dir: ../logs
#model_dir: ../models
config: ../config/config.yml
train_source: ../data/7k_BPE_indexed/train/source.train.pickle
train_target: ../data/7k_BPE_indexed/train/target.train.pickle
dev_source: ../data/7k_BPE_indexed/dev/source.dev.pickle
dev_target: ../data/7k_BPE_indexed/dev/target.dev.pickle
strategy: None
zero_bias: false
bpe_ops: 7000
joined_bpe: false
window_size: 3
batch_alignment: uniform
n_checkpoint: 1
n_evaluate: 1
checkpoints_per_epoch: 0
early_stopping : false
early_stopping_threshold: 0.1
beam_size : 1
max_decoding_time_step : 1
raw_dev_target: ../data/unpreprocessed/dev/target.dev
raw_dev_source: ../data/unpreprocessed/dev/source.dev
